---
name: Download latest spec and regenerate JSON

on:
  # Run this workflow at 00:00 every day
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update upstream and run
        run: ./x update-upstream && ./x run
      - name: Check for changes
        id: check
        run: |
          if [ $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push
        if: steps.check.outputs.no_changes == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Regenerate spec $(date '+%d.%m.%Y')"
          git push


